workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: python:3.12


stages:
  - test

default:

  before_script:
      - pip install -r requirements.txt

  tags:
      - python-runner

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy homework/

black:
  stage: test
  script:
    - black --diff --check  homework/

isort:
  stage: test
  script:
    - isort --check-only  homework/

flake8:
  stage: test
  script:
    - flake8  homework/